export const QUERY_KEY = {
  ALL_CATEGORIES: "ALL_CATEGORIES",
  SINGLE_CATEGORY_POKEMONS: "SINGLE_CATEGORY_POKEMON",
  ALL_POKEMONS: "ALL_POKEMON",
  SINGLE_POKEMON: "SINGLE_POKEMON",
};

export const colors = ["#3b82f6", "#0284c7", "#a855f7", "#f472b6", "#14b8a6"];
